[server]
enableStaticServing = true

[theme]
base = "dark"
primaryColor = "#FF6B6B"
backgroundColor = "#020204"
secondaryBackgroundColor = "#151217"
textColor = "#FFFFFF"

[[theme.fontFaces]]
family = "JetBrains Mono"
url = "static/fonts/JetBrainsMono-Regular.woff2"
style = "normal"
weight = 400

[[theme.fontFaces]]
family = "JetBrains Mono"
url = "static/fonts/JetBrainsMono-SemiBold.woff2"
style = "normal"
weight = 600

[[theme.fontFaces]]
family = "JetBrains Mono"
url = "static/fonts/JetBrainsMono-Bold.woff2"
style = "normal"
weight = 700
